# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
        migrations.AlterField(
            model_name='login_data',
            name='user_id',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
