# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions_data',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_name', models.CharField(blank=True, max_length=120, null=True)),
                ('q_question', models.TextField(blank=True, null=True)),
                ('q_type', models.CharField(blank=True, max_length=120, null=True)),
                ('q_max_time', models.TimeField()),
                ('q_max_memory', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
