# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_password', '0002_auto_20161028_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgot_data',
            name='user_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
