# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=120)),
                ('user_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('roll_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sem', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
